### ISSUE TITLE
Update User Guide, Landing Page (Index.html)

### ISSUE THREAD

**Issue by Yufannnn** [AY2223S2-CS2103T-W13-4/tp#104]
Update the v1.3 user guide to match the current version of the product. Reason: testers will need to refer to the UG during the practical exam dry run.
Remove mentions of any features not implemented yet, if any. As you are not allowed to change features during iteration v1.4, there is no point in keeping those in the UG.
For those features already implemented, ensure their descriptions match the exact behavior of the product e.g. replace mockups with actual screenshots
Landing page (docs/index.md): Update to look like a real product (rather than a project for learning SE) if you haven't done so already. In particular, update the Ui.png to match the current product ( tips).

**Comment by Yufannnn** [comment]
Please update the User Guide to include the new commands and features that you have implemented. Also, update the index.html if it is necessary.

**Comment by szejiancheng** [comment]
Will wait for all User Guide elements to be in before updating landing page and subsequently closing issue
