### ISSUE TITLE
[PE-D][Tester C] Differs From UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W13-4/tp#131]
![Screen Shot 2023-03-31 at 14.04.19 PM.png](https://raw.githubusercontent.com/SFCoding123/ped/main/files/5316ac0a-48e4-4dae-b114-18a9605e9c2b.png)

UserGuide claims delete-b 1 but it is not recognized. 

The actual Command Line is delete 1.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: SFCoding123/ped#1

**Comment by fahim-tazz** [comment]
Need to add `delete` section in UG, and remove `delete-b` keyword in GUI section

**Comment by fahim-tazz** [comment]
Fixed. Removed `delete-b` from UG.
