### ISSUE TITLE
[PE-D][Tester C] Invalid Command update-info

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W13-4/tp#132]
![Screen Shot 2023-03-31 at 14.16.36 PM.png](https://raw.githubusercontent.com/SFCoding123/ped/main/files/634b263a-7061-4b11-95ba-b3d390fcf3e5.png)

Example Command from UG is invalid.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: SFCoding123/ped#2

**Comment by fahim-tazz** [comment]
The command exists as `edit`, I'll update accordingly.
