### ISSUE TITLE
[PE-D][Tester A] UG Table is not properly formatted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W13-4/tp#154]
I understand this issue is actually quite prevalent across many UGs. Could be a html rendering issue.

Still, documenting it here as a reminder :)

![Screenshot 2023-03-31 at 2.47.28 PM.png](https://raw.githubusercontent.com/4ndrelim/ped/main/files/b4edcab4-e0de-422f-8539-6d113a70e5cf.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: 4ndrelim/ped#5

**Comment by fahim-tazz** [comment]
Fixed UG table formatting
