### ISSUE TITLE
[PE-D][Tester D] Assign Homework rejects date format 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W13-4/tp#155]
![image.png](https://raw.githubusercontent.com/tyx021/ped/main/files/76105f5c-be1d-4364-894f-8a6ca1294c35.png)

Command executed:

`new-homework name/John homework/listening comprehension ex1 deadline/02-12-2023 2359`

According to User Guide, the data format `dd-mm-yyyy HHmm` should be accepted 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tyx021/ped#9

**Comment by Yufannnn** [comment]
Fixes Issue by updating the date parser
