### ISSUE TITLE
[PE-D][Tester D] `calculate-grade` unknown command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W13-4/tp#160]
![image.png](https://raw.githubusercontent.com/tyx021/ped/main/files/f63444dc-a8fb-4d8d-b184-58216421d427.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tyx021/ped#12

**Comment by fahim-tazz** [comment]
Calculate grade was removed from the app.

**Comment by fahim-tazz** [comment]
Removed from UG.
