### ISSUE TITLE
[PE-D][Tester B] Date Time format unrecognised though followed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W13-4/tp#163]
Even though the date time is input according to the last format provided the command is not recognised to work.

![2023-03-31 (9).png](https://raw.githubusercontent.com/Cheamybunny/ped/main/files/ea0f057d-bcec-4ce6-803c-c53650b98635.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Cheamybunny/ped#8

**Comment by Yufannnn** [comment]
Fixes Issue by updating the date parser
