### ISSUE TITLE
[PE-D][Tester A] Unexpected Update Result

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W13-4/tp#165]
Updating a homework (eg its name field) might change its completion status. Granted, there may be some justification or argument (eg there isn't a need to update a homework once completed. In which case, maybe can ban the editing of a completed homework) for this but the word 'update' suggests nothing else aside from the desired changes should change. Alternatively, perhaps can consider documenting in the UG to avoid doubts.

![Screenshot 2023-03-31 at 3.17.52 PM.png](https://raw.githubusercontent.com/4ndrelim/ped/main/files/bae62aec-30d8-4ecf-952d-b44a09eb67b5.png)

![Screenshot 2023-03-31 at 3.14.34 PM.png](https://raw.githubusercontent.com/4ndrelim/ped/main/files/85928cb5-59c2-42f8-9b3f-7245a7e53733.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: 4ndrelim/ped#8

**Comment by Yufannnn** [comment]
Fixed Issue by updating the Update-homework command.
