### ISSUE TITLE
Bug- Date parsing not working

### ISSUE THREAD

**Issue by szejiancheng** [AY2223S2-CS2103T-W13-4/tp#171]
![image](https://user-images.githubusercontent.com/55904848/229299070-3f44fa5e-bca2-4b6d-b660-26b70e5b1024.png)

**Comment by Yufannnn** [comment]
I don't know why the parser somehow cannot parse this format of DateTime. Anyway, I removed this format. the other formats are all working well, I have tested them all. You can also help me test the date format if you have time.
